version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: tennis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: your_user
      DB_PASSWORD: your_password
      DB_NAME: tennis_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: